name: AmkMcAuth
main: com.mooo.amksoft.amkmcauth.AmkMcAuth
version: 1.5.3
api-version: 1.15
author: AmkSoft (fork/continuation of RoyalAuth plugin by jkcclemens). 
website: https://amksoft.mooo.com/minecraft/plugins
description: A security-based plugin that locks player accounts with passwords that must be entered before the player can play.
             This plugin is based on the RoyalAuth plugin created by jkcclemens. AmkSoft updated it to work under MC 1.9+ . 

commands:
  amkmcauth:
    description: (AmkMcAuth) Provides access to administrative functions of the plugin.
    usage: /<command> [subcommands|help]
    aliases: [amka, amkauth]
  login:
    description: (AmkMcAuth) Logs a player in.
    usage: /<command> [password]
    aliases: [l, logon]
  logout:
    description: (AmkMcAuth) Logs a player out.
    usage: /<command>
    aliases: [lo, logoff]
  register:
    description: (AmkMcAuth) Register a players password or emailaddress.
    usage: /<command> [password/emailaddress]
    aliases: [reg]
  setemail:
    description: (AmkMcAuth) Changes a player's Email-Address.
    usage: /<command> [emailaddress]
  setrecover:
    description: (AmkMcAuth) Sets players Recover Question + Answer.
    usage: /<command> [QuestionText=Answer]
  changepassword:
    description: (AmkMcAuth) Changes a player's password.
    usage: /<command> [oldPassword] [newPassword]
    aliases: [chpw, cpwd, changepass, passchange]
  recoverpwd:
    description: (AmkMcAuth) recover player's login by sending new password to player's Email-Address or Checking Recover Answer.
    usage: /<command> [<your answer> | email | question] 

permissions:
  amkauth.login:
    description: Allows use of /login
    default: true
  amkauth.logout:
    description: Allows use of /logout
    default: true
  amkauth.register:
    description: Allows use of /register
    default: true
  amkauth.changepassword:
    description: Allows use of /changepassword
    default: true
  amkauth.amkmcauth:
    description: Allows use of /amkauth
    default: op
  amkauth.nlpwd:
    description: controls the NoLoginPassWrD on Login (if not set via nlpwdadd)
    default: false
  amkauth.user:
    description: Contains all permission nodes for non-administrative functions
    default: false
    children:
      amkauth.login: true
      amkauth.logout: true
      amkauth.register: true
      amkauth.changepassword: true
      amkauth.nlpwd: false
  amkauth.*:
    description: Contains every permission node in AmksoftMcAuth
    default: false
    children:
      amkauth.user: true
      amkauth.amkmcauth: true
